import Head from "next/head"
import styled from "styled-components"
import React from "react"

export default function Home() {
  return (
    <>
      <Head>
        <title>WhatsApp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App>
        <Container></Container>
      </App>
    </>
  )
}

const App = styled.div`
  background-color: #dbdbd4;
  width: 100%;
  height: 100vh;
  position: relative;
  :after {
    width: 100%;
    height: 127px;
    background-color: #009688;
    content: '';
    position: absolute;
    top: 0;
  }
`
const Container = styled.div`
  width: 100%;
  height: calc(100vh - 38px);
  background-color: #fff;
  max-width: 1396px;
  position: absolute;
  top: 19px;
  z-index: 1;
  left: 50%;
  transform: translateX(-50%);
`
